<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="meldas-MBP.local.tld" failures="1" tests="3" name="Command line test" time="15.764" errors="0" timestamp="2022-05-21T15:14:17 CDT">
  <testcase classname="scripts._01_AppleTest" name="X" time="0.002">
    <failure type="java.lang.AssertionError" message="Failure on purpose">
      <![CDATA[java.lang.AssertionError: Failure on purpose
at scripts._01_AppleTest.X(_01_AppleTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- X -->
  <testcase classname="scripts._01_AppleTest" name="testAppleTitle" time="0.912"/>
  <testcase classname="scripts._01_AppleTest" name="testAppleURL" time="0.751"/>
</testsuite> <!-- Command line test -->
